package ru.geekbrains.easynotes.exceptions

class NoAuthException : Throwable()